import {useState, useEffect} from 'react'

import Head from 'next/head'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {
  const RANDOM_QUOTE_URL = 'https://api.quotable.io/random'
  const [quoteData, setQuoteData] = useState()
  const [numOfQuotesLoaded, setNumOfQuotesLoaded] = useState(0)

  // on mount I want you to get the random quote.
  useEffect(()=> {
    console.log("Mounted")
    // so that when I load the page I see the quote immediately.
    getRandomQuote()
  }, []) // empty dependency array means on mount.

  // I want you to listen to the changes of quoteData
  useEffect(()=> {
    // if the quote data is undefined then don't do the rest
    if (!quoteData) { return }

    console.log("quoteData has changed")
    console.log(quoteData)

    // I want you to update the numOfQuotesLoaded
    setNumOfQuotesLoaded(numOfQuotesLoaded+1)
  }, [quoteData])

  const getRandomQuote = async () => {
    const response = await fetch(RANDOM_QUOTE_URL)
    const data = await response.json()
    setQuoteData({
      quote: data.content,
      author: data.author
    })
  }

  // return early if you don't have any quote data
  if (!quoteData) {
    // below you can use a spinner to essentially handle this.
    return <h2>Loading ...</h2>
  }

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Typography
              component="p"
              variant="p"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              The number of quotes loaded in this session is
              {" " +numOfQuotesLoaded}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={getRandomQuote}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
